plugins {
    id 'org.springframework.boot' version '3.2.5'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'java'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
}

// core-domain est une lib, pas une app bootable
bootJar.enabled = false
jar.enabled = true